# Generated by Django 3.2.5 on 2021-08-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_profile_cf_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cf_rating',
            field=models.IntegerField(editable=False),
        ),
    ]
