# Generated by Django 3.2.5 on 2021-08-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_profile_cf_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cf_rating',
            field=models.IntegerField(default=0),
        ),
    ]
