# Generated by Django 3.2.5 on 2021-08-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20210804_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
