# Generated by Django 3.2.5 on 2021-08-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_slideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
