# Generated by Django 3.2.5 on 2021-08-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_alter_slideshow_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
